### ISSUE TITLE
Can you update the 2.x sketch file to latest clarity?

### ISSUE THREAD

**Issue by kumar-tadepalli** [vmware/clarity-assets#2]
There are few new components added in clarity.
Is it possible to update update the 2.x sketch file to latest clarity with new components?

**Comment by mathisscott** [comment]
@reddolan 
Have we updated our files with the new components?

**Comment by reddolan** [comment]
Issue #3628: https://github.com/vmware/clarity/issues/3628 has the updated resources. We plan to have the site updated soon with the files.

**Comment by reddolan** [comment]
Are there specific components that you were looking for? The Accordion and Timeline were added in the 2.2.0 files

**Comment by kumar-tadepalli** [comment]
Mutiselect component is missing.

**Comment by reddolan** [comment]
If by multiselect you mean Datalist, that is going to be only in Figma. With 3.0 Clarity will deprecating support to the Sketch libraries

**Comment by gnomeontherun** [comment]
I think we can close this, as we won't be updating Sketch for v3 and the new components are in v3.
